version: '3.8'
services:
  client-web:
    build:
      context: ./apps/client-web
      dockerfile: Dockerfile
    image: e-commerce-client-web
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    expose:
      - 4000
    depends_on:
      - api
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    image: e-commerce-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    expose:
      - 3000
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - client-web
      - api
